# Use Node.js version 20.12.2 as the base image for building frontend
FROM node:20.12.2 

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files from frontend-app/ directory
COPY package.json .

# Install frontend dependencies
RUN npm install

# Copy the rest of your frontend code from frontend-app/
COPY . .

# Expose the port your frontend app runs on (assuming your app listens on port 3000)
EXPOSE 3000

# Command to run your frontend app
CMD ["npm", "start"]
