
FROM node:20.12.2

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package.json .

# Install dependencies
RUN npm install
RUN npm install -g nodemon
# Copy the rest of your backend code
COPY . .

# Expose port 5000
EXPOSE 5000

# Command to run nodemon for development with live reload
CMD ["nodemon", "--watch", ".", "--legacy-watch", "index.js"]
